// src/components/Card.tsx
import React from "react";
import styled from "styled-components";

const Container = styled.div`
    background-color: var(--background-secondary);
    width: 100%;
    aspect-ratio: 1.1;
    overflow: hidden;
    &:hover {
        background-color: var(--background-secondary-alt);
    }
`;

// TODO(tkat0): Support star
// height: 10 + 10 + 20 + 10 = 50px
const Header = styled.div`
    border-top: var(--background-modifier-border) solid 10px;
    padding: 10px 12px;
`;

const Title = styled.div`
    text-overflow: ellipsis;
    font-weight: 500;
    max-height: 20px;
    font-size: 14px;
    overflow: hidden;
    white-space: nowrap;
    color: var(--text-accent);
`;

const Contents = styled.div`
    overflow: hidden;
    /* Container - Header (50px) - margin (5px) */
    height: calc(100% - 55px);
    margin: 0 10px 0;
`;

const Thumbnail = styled.img`
    overflow: hidden;
    height: 100%;
    display: block;
    margin: auto;
    padding: 0 5px;
`;

const Description = styled.div`
    overflow: hidden;
    height: 100%;
    line-height: 20px;
    font-size: 12px;
`;

const Line = styled.p`
    display: inline;
`;

export interface CardProps {
    title: string;
    thumbnail: string | undefined;
    description: string[];
    onClick: () => void;
}

export const Card = (props: CardProps) => {
    const { title, thumbnail: icon, description, onClick } = props;
    return (
        <Container onClick={onClick}>
            <Header>
                <Title>
                    <a>{title}</a>
                </Title>
            </Header>
            <Contents>
                {icon ? (
                    <Thumbnail loading="lazy" src={icon}></Thumbnail>
                ) : (
                    <Description>
                        {description.map((line) => (
                            <Line>{line}</Line>
                        ))}
                    </Description>
                )}
            </Contents>
        </Container>
    );
};

// packages/grid-view/src/view/Card.svelte
<script lang="ts">
  import type { Description } from '../domain/model';

  export let title: string;
  export let description: Description[][];
  export let icon: string | undefined = undefined;
  export let star = false;
  export let width: number;
  export let onClick: () => void;
</script>

<div
  class="bg-background-secondary hover:bg-background-secondary-alt relative aspect-square overflow-hidden"
  style="width: {width}px;"
  on:click={onClick}
>
  {#if star}
    <div
      class="border-r-background-primary border-b-text-accent absolute top-0 right-0 h-0 w-0 border-b-[30px] border-r-[30px] border-solid shadow-xl"
    />
  {/if}
  <div
    class="border-t-background-modifier-border h-[calc(100%-5px)] overflow-hidden border-t-[15px] border-solid py-2 px-3"
  >
    <div class="text-text-accent max-h-5 overflow-hidden text-ellipsis whitespace-nowrap font-medium">
      {title}
    </div>
    <div class="mx-2 my-2">
      {#if icon}
        <img class="m-auto block h-full overflow-hidden px-1 py-0" loading="lazy" src={icon} alt={title} />
      {:else}
        <div class="h-full overflow-hidden text-xs leading-5">
          {#each description as line}
            <div class="line">
              {#each line as node}
                <span class={node.kind}>{node.value}</span>
              {/each}
            </div>
          {/each}
        </div>
      {/if}
    </div>
  </div>
</div>

<style>
  .code {
    background-color: var(--background-primary-alt);
    color: var(--text-accent);
  }

  .link {
    color: var(--text-accent);
  }

  .emphasis {
    font-weight: var(--bold-weight);
  }
</style>
